import { Link } from "react-router-dom";

const UPDATED = "19 September 2026";

export function PrivacyPolicy() {
  return (
    <div className="safe-top safe-bottom px-5 pb-10">
      <Link to="/" className="text-sm text-[var(--gold)]">
        ← Home
      </Link>
      <p className="kicker mt-5">Legal</p>
      <h1 className="serif mt-1 text-[2.1rem] font-semibold">Privacy policy</h1>
      <p className="mt-2 text-sm text-[var(--muted)]">Last updated {UPDATED}</p>

      <article className="mt-6 space-y-5 text-sm leading-relaxed text-[#d8d2c6]">
        <p>
          Aurea is a travel planning app. This policy explains what we collect, what we send to other companies, and
          what stays on your phone. It is written for Google Play and for you.
        </p>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Who we are</h2>
          <p className="mt-2">
            Aurea (package <span className="text-[var(--gold-bright)]">com.aurea.travel</span>) is operated by the
            developer who published this listing. Contact: the email on the Play Store listing.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">What stays on your device</h2>
          <p className="mt-2">
            Your name, home city, currency, chat history, and saved trips are stored in app storage on this phone
            (browser local storage). We do not run a user account. Clearing app data or uninstalling deletes that
            history unless you shared a copy.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">What we send over the internet</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>
              <strong className="text-[var(--gold-bright)]">Google Gemini.</strong> Questions you Ask and details you
              enter on Plan (destination, dates, travelers, budget, notes, profile name/city/currency) are sent to our
              server, then to Google so the model can write a reply. Google’s terms apply to that processing. Do not
              type passport numbers, card numbers, or passwords.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">OpenStreetMap / Nominatim / Overpass.</strong> The place you
              type is sent to look up cities, hotels, restaurants, and sights. Map data © OpenStreetMap contributors,
              ODbL.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Open-Meteo.</strong> Coordinates of the destination are sent
              for a weather forecast.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Wikipedia.</strong> The city name may be used to fetch a
              short public summary.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Aurea activity log.</strong> Our server stores the name and
              home city you typed, a device id, timestamps, and what you asked or planned (destination or a short
              question snippet). This is so we can operate the app. We do not sell it. Records are kept up to 90 days.
            </li>
          </ul>
          <p className="mt-2">
            Booking.com, Airbnb, Zomato, and Google Maps open in the browser when you tap Book or Maps. Those sites
            have their own policies. Aurea does not take hotel payments.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">AI-generated content</h2>
          <p className="mt-2">
            Itineraries, budgets, and visa steps are generated by AI. They can be wrong. Visa steps are information
            only — you apply yourself on the official government site. Aurea is not a visa agent, airline, or travel
            insurer.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Children</h2>
          <p className="mt-2">Aurea is not directed at children under 13. Do not use the app if you are under 13.</p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Your choices</h2>
          <p className="mt-2">
            You can edit your profile, delete a trip, start a new chat, or uninstall the app. We do not sell personal
            data. We do not show third-party ads.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Changes</h2>
          <p className="mt-2">If this policy changes, we will update the date above and the copy in the app.</p>
        </section>
      </article>
    </div>
  );
}
