import { Link } from "react-router-dom";

const UPDATED = "22 September 2026";

export function PrivacyPolicy() {
  return (
    <div className="safe-top safe-bottom px-5 pb-10">
      <Link to="/" className="text-sm text-[var(--gold)]">
        ← Home
      </Link>
      <p className="kicker mt-5">Legal</p>
      <h1 className="serif mt-1 text-[2.1rem] font-semibold">Privacy policy</h1>
      <p className="mt-2 text-sm text-[var(--muted)]">Last updated {UPDATED}</p>

      <article className="mt-6 space-y-5 text-sm leading-relaxed text-[#d8d2c6]">
        <p>
          Safar is a travel planning app. This policy explains what we collect, what we send to other companies, and
          what stays on your phone. It is written for Google Play and for you.
        </p>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Who we are</h2>
          <p className="mt-2">
            Safar (package <span className="text-[var(--gold-bright)]">com.safar.travel</span>) is operated by the
            developer who published this listing. Contact: the email on the Play Store listing.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">What stays on your device</h2>
          <p className="mt-2">
            Safar also keeps a copy of your profile, chats, and trips on this phone so the app works offline. Logging
            out clears that copy. Your account copy stays in our database until you ask us to delete it.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Google account</h2>
          <p className="mt-2">
            You must sign in with Google to use Safar. Google shares your name, email, and profile photo. We store those
            plus your chats and saved trips so they reload on another device. Log out from Profile. We do not get your
            Google password.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">What we send over the internet</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>
              <strong className="text-[var(--gold-bright)]">Google Gemini.</strong> Questions you Ask and details you
              enter on Plan (destination, dates, travelers, budget, notes, profile name/city/currency) are sent to our
              server, then to Google so the model can write a reply. Google’s terms apply to that processing. Do not
              type passport numbers, card numbers, or passwords.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">OpenStreetMap / Nominatim / Overpass.</strong> The place you
              type is sent to look up cities, hotels, restaurants, and sights. Map data © OpenStreetMap contributors,
              ODbL.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Open-Meteo.</strong> Coordinates of the destination are sent
              for a weather forecast.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Wikipedia.</strong> The city name may be used to fetch a
              short public summary.
            </li>
            <li>
              <strong className="text-[var(--gold-bright)]">Safar activity log.</strong> Our server stores the name and
              home city you typed, a device id, timestamps, and what you asked or planned (destination or a short
              question snippet). Plan searches (destination, dates, travelers, budget, style) are stored even if you do
              not tap Save. The operator account can review activity and chat transcripts to run the product. We do not
              sell it. Records in the activity log are kept up to 90 days.
            </li>
          </ul>
          <p className="mt-2">
            Booking.com, Airbnb, Zomato, and Google Maps open in the browser when you tap Book or Maps. Those sites
            have their own policies. Safar does not take hotel payments.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">AI-generated content</h2>
          <p className="mt-2">
            Itineraries, budgets, and visa steps are generated by AI. They can be wrong. Visa steps are information
            only — you apply yourself on the official government site. Safar is not a visa agent, airline, or travel
            insurer.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Children</h2>
          <p className="mt-2">Safar is not directed at children under 13. Do not use the app if you are under 13.</p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Your choices</h2>
          <p className="mt-2">
            You can edit your profile, delete a trip, start a new chat, or tap Delete account on Profile. That removes
            your Google-linked profile, chats, and saved trips from Safar. You can also uninstall the app. We do not
            sell personal data. We do not show third-party ads.
          </p>
        </section>
        <section>
          <h2 className="serif text-xl font-semibold text-[var(--cream)]">Changes</h2>
          <p className="mt-2">If this policy changes, we will update the date above and the copy in the app.</p>
        </section>
      </article>
    </div>
  );
}
